### ISSUE TITLE
Double slash on one sourcemap?

### ISSUE THREAD

**Issue by butaminas** [thredup/rollbar-sourcemap-webpack-plugin#197]
This is my config in webpack (with replaced example values):

```
new RollbarSourceMapPlugin({
  accessToken: token-here,
  version: version-here,
  publicPath: domain.com
})
```

It seems to upload all of the sourcemaps correctly except for one - app.js file. It is also uploaded correctly but the path is 

> //domain.com**//**js/app.js

when it should be

> //domain.com**/**js/app.js

Therefore, when an error is submitted to rollbar, I get that no sourcemap was found for 

> //domain.com**/**js/app.js

Why do I get the double slash added and how can I fix this?

Here is how my sourcemaps look at rollbar.com:

![](https://user-images.githubusercontent.com/10225960/86787281-9ad77080-c06d-11ea-8282-90e5f3d167ff.png)

**Comment by butaminas** [comment]
I figured it out.  
I was using laravel-mix for webpack and for some reason it was adding additional slash to the path.  
Also, there was a problem with my versioning, the submitted version through the API had quotes and the front-end didn't.  
  
For future reference, I fixed the double slash problem by adding this to my webpack / laravel-mix config:  
`mix.override(config => {`  
 `config.entry = Object.keys(config.entry).reduce((acc, key) => {`  
 `acc[key.replace(/^\//, "")] = config.entry[key]`  
 `return acc`  
 `}, {})`  
`})`

**Comment by brandondoran** [comment]
Ok @butaminas, thanks for the update.

**Comment by philbates35** [comment]
For anyone else that comes across this double slash issue when using laravel-mix with this plugin, rather than fixing the issue by using `mix.override()` like in https://github.com/thredup/rollbar-sourcemap-webpack-plugin/issues/197#issuecomment-655419887 to change the entry name, I found it cleaner to use the function form of the `publicPath` property to strip the leading slash at the point the soucemap file name is determined:

```js
new RollbarSourceMapPlugin({
    publicPath: sourceFile => 'https://dynamichost/' + sourceFile.replace(/^\//, ''),
})
```
Ideally it would be nice if this plugin worked with chunks that start with a leading slash too, but I don't know enough about this project to submit an MR.
