### ISSUE TITLE
Does it support Rollbar version 2? And with webpack 2.0 cannot upload file successfully

### ISSUE THREAD

**Issue by ShirleyYoung0926** [thredup/rollbar-sourcemap-webpack-plugin#38]
Does this plugin support rollbar version 2 ? When I try to found rollbar-browser in npm, only "rollbar": "2.0.4".

Now I use rollbar-browser and webpack 2, it showed
Uploaded XXX.ca606eb3630a8f898d78.js.map to Rollbar
Uploaded vendor.bundle.ca606eb3630a8f898d78.js.map to Rollbar
But when I go to Rollbar settings/source_map I cannot download i. It seems I didnot upload successfully. And if I upload manually, I can download it. Therefore, there must be something wrong with uploading. How can I dig deeper for this issue?

**Comment by brandondoran** [comment]
Yes, this plugin works in Webpack 2.

This plugin has no direct dependency on the https://github.com/rollbar/rollbar.js npm module. However, It has not been tested with projects using the new rollbar v2.  I suspect it should work with rollbar v2 since this plugin uploads sourcemaps via the http endpoint documented [here](https://rollbar.com/docs/source-maps/). Can you double check the `accessToken` you're using for the plugin is the correct one for your rollbar project?  If any http error or non 200 response occurs, the plugin should report an error.

**Comment by ShirleyYoung0926** [comment]
![screen shot 2017-06-23 at 3 39 58 pm](https://user-images.githubusercontent.com/23160157/27471588-cd2ff10a-582a-11e7-97fa-d705c48fcb36.png)

![screen shot 2017-06-23 at 3 37 20 pm](https://user-images.githubusercontent.com/23160157/27471578-c42f4ee8-582a-11e7-81a6-ed62d677f52f.png)

I double checked the accessToken both for client and for server, they are all right. As above pictures shows, there are no errors during webpack building, and I can see two source map files logs on rollbar. And the only problem is I cannot download it. When I click download, I will be redirected to 404 page, as shown in the below picture.
![screen shot 2017-06-23 at 3 46 51 pm](https://user-images.githubusercontent.com/23160157/27471704-390594de-582b-11e7-8fe1-b4781ac3ddac.png)

**Comment by lambertkuang** [comment]
I'm on `"rollbar": "~2.2.3",` and I'm able to download the source map but the 'Minified Url' link takes me to their 404 page... anyone else have this issue as well?

**Comment by SamanthaAdrichem** [comment]
The issue i have is that webpack doesn't seem to generate the 'names' section in the sourcemaps. And therefor it doesn't upload.
