### ISSUE TITLE
Two source maps not being uploaded

### ISSUE THREAD

**Issue by pdcmoreira** [thredup/rollbar-sourcemap-webpack-plugin#72]
I'm using this with Vue.js and my config is like this:

```js
const RollbarSourceMapPlugin = require('rollbar-sourcemap-webpack-plugin')

module.exports = {
  configureWebpack: {
    plugins: [
      new RollbarSourceMapPlugin({
        accessToken: '...',
        version: '1.0',
        publicPath: '/'
      })
    ]
  }
}
```

On build, the console outputs the uploaded maps, which include:
```
Building for production...Uploaded js/app.2cdc0d24.js.map to Rollbar
Building for production...Uploaded js/chunk-vendors.67ce8235.js.map to Rollbar
```

After I intentionally trigger an exception in the app, I can see this in the "Source Maps" configuration page on Rollbar:
![image](https://user-images.githubusercontent.com/4430606/72562600-b4101900-38a3-11ea-972f-b9f1bca06134.png)

Other maps appear to be good:
![image](https://user-images.githubusercontent.com/4430606/72562643-cc803380-38a3-11ea-9c20-96b075169a89.png)

Also, on the occurrence page, I can see this message on top:
`Source maps were not available for some minified Javascript files in this traceback. View your project source maps or check out the source map docs.`

**Comment by brandondoran** [comment]
Hi, I believe the problem is in the config for `RollbarSourceMapPlugin`. `publicPath` should be the public location where your assets are published, like a CDN. Rollbar isn't able to access your localhost.

Also, `version` should be a unique string for every build. The same should be used for `code_version` in the config for the rollbar client itself. Typically you'd use the git sha for this.

Just to clarify how this should work:
* JS assets are compiled, minified, and uploaded to a CDN.
* You don't want to upload sourcemaps along with the minified source. The minified source should have a comment that specifies the sourcemap file name, such as `//# sourceMappingURL=app.10b68db1f21770fbad54.js.map`
* Sourcemaps are uploaded to Rollbar via this plugin. Included with each sourcemap are the url to the minified file (on CDN or other public domain) and the `version`.
* The same `version` used for the sourcemap upload must be used for `code_version` in the rollbar client config.  It's up to you do do this. It depends on how you use rollbar - as npm package or snippet of JS pasted in html.
* When there's a runtime error, Rollbar's backend links up the uploaded sourcemap with the minified url and gives you back stacktraces and error line numbers that map back to the original, unminified source.
